name: alwan
description: danmaklen.com UI.

version: 1.0.3

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^5.5.0+1
  get_it: ^8.0.3
  go_router: ^15.1.3
  provider: ^6.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
