name: alwan
description: danmaklen.com UI.

version: 1.0.1+2

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  flutter_spinbox: ^0.8.0
  flutter_flavor: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
