name: alwan
description: danmaklen.com UI.

version: 1.0.2+3

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^5.3.3
  get_it: ^7.6.4
  go_router: ^14.2.0
  provider: ^6.1.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
