name: CD
on:
  workflow_run:
    workflows: CI
#    branches: master
    types: completed

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy Infrastructure
        run: echo "Hello World"
  deploy-alwan:
    name: Deploy Alwan
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          - workflow: CI
      - run: ls
      - name: Deploy Alwan

        run: echo "Hello World"
