name: CICD
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.x'
          channel: 'stable'
          cache: true
      - name: Using Flutter Version
        run: flutter --version
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Release
        run: flutter build web --release
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: alwanReleaseBuildArtifact
          path: build/web

  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    container: contino/aws-cdk
    #    if: github.ref == 'refs/heads/master'
#    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Deploy Infrastructure
        run: |
          cdk deploy \
            --app=Alwan.Infra \
            --require-approval never \
            --outputs-file $outputFile \
            -c Name="Alwan" \
            -c DomainName="danmaklen.com" \
            -c CertificateArn="${{secrets.CertificateArn}}"
      - run: "echo 'Reminder: add CNAME record to your domain \`$domainName\` with value \`$edgeDomain\`'"
      - run: "echo '::setOutputs name=bucketArn::$bucketArn'"
  deploy-alwan:
    name: Deploy Alwan
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/master'
    needs: deploy-infra
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: alwanReleaseBuildArtifact
          path: build/web
      - run: ls
      - name: Deploy Alwan
        run: echo "Hello World"
