name: Alwan CICD
on:
  push:
    branches:
      - master
  pull_request: {}
  merge_group:
    types: [ checks_requested ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "eu-west-1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - uses: actions/checkout@v3
      - run: flutter pub get
      - run: dart run build_runner build
      - run: flutter build web --dart-define-from-file=lib/config/prod.json --release
      - uses: actions/upload-artifact@v4
        with:
          name: alwanReleaseBuildArtifact
          path: build/web

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: alwanReleaseBuildArtifact
      - run: aws s3 sync . s3://alwan --delete
      - run: aws cloudfront create-invalidation --distribution-id ERUCS7JYAPAOD --paths '/*'
