name: CICD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.x'
          channel: 'stable'
      - run: flutter --version
      - name: Build Release
        run: flutter build web --release
